### ISSUE TITLE
Have a screenshot in the README

### ISSUE THREAD

**Issue by MorrisJobke** [opensourcedesign/slick#6]
This helps to increase the interest in this project once you found it ;)

**Comment by jancborchardt** [comment]
Do you have it installed? You’re welcome to take the screenshot and put it in. :)

**Comment by MorrisJobke** [comment]
Nope ... I first want the screenshot to evaluate if it is worth to install :P

**Comment by gillisig** [comment]
@MorrisJobke since @bnvk just starting working on it a couple of days ago, I don't think he has it at a stage where it is screenshot worthy yet. 

But its a good idea to add it once its ready. :+1:

**Comment by MorrisJobke** [comment]
After following the steps in the readme, I get:

```
undefined:13
((__t = ( channelsActionable )) == null ? '' : __t) +
          ^
ReferenceError: channelsActionable is not defined
    at eval (eval at template (/home/mjob/Projekte/shout/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:13:11)
    at Function.template (/home/mjob/Projekte/shout/node_modules/lodash/dist/lodash.js:6312:16)
    at /home/mjob/Projekte/shout/src/server.js:82:13
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

cc  @bnvk

**Comment by MorrisJobke** [comment]
WIth the standard theme it works just fine. Once I switch it and reload the page I got the message above.

**Comment by jancborchardt** [comment]
@MorrisJobke new issue please ;)

**Comment by MorrisJobke** [comment]
#8 ;)

**Comment by pdurbin** [comment]
A couple more votes for a screenshot: https://botbot.me/freenode/opensourcedesign/msg/40026624/

**Comment by nhooyr** [comment]
How has no one posted a single screenshot yet LOL

edit: whoops, didn't see note in README

**Comment by jancborchardt** [comment]
@nhooyr everyone is welcome to contribute :)
